### ISSUE TITLE
App crash with IQ! just after displaying data

### ISSUE THREAD

**Issue by SylvainGa** [srwalter/garmin-tesla#20]
Watch is a Venu, software 6.3. Car is a Tesla Model 3. It does manage to connect but crashes a fraction of a second after displaying this (data is valid)

![image](https://user-images.githubusercontent.com/49377866/132968198-6becb0ba-675f-418f-9cf4-0e4d808ec14f.png)

Token taken from Tesla Token on Android. Tesla app works correctly on phone.

**Comment by paulobrien** [comment]
Hi Sylvain, drop me a DM on Twitter (@paulobrien), and I'll send you a new version to test.

**Comment by SylvainGa** [comment]
Latest built fixed the issue. Thanks Paul for the quick response.
