### ISSUE TITLE
Couldn't access 'Settings' with v6.0

### ISSUE THREAD

**Issue by purcell-lab** [srwalter/garmin-tesla#22]
I have just upgraded to v6 on a Fenix 6 Pro and can't see where to access settings, my widget glances always says  'Status Unknown'.

I would like to access Settings to switch to icon view and charger port unlock.

Previously I accessed Settings via ConnectIQ to enter my API token. When I installed v6 it took me through the Tesla login page so all good there.

![Screenshot_20211107-195825](https://user-images.githubusercontent.com/79175134/140638754-81748b68-0675-43df-9e1d-4873900048e1.png)

**Comment by paulobrien** [comment]
Touch the bottom right of the screen to see the menu.

**Comment by purcell-lab** [comment]
>
> Touch the bottom right of the screen to see the menu
>
I don't have a touch screen on my Fenix 6, the bottom right button is the
back button and hours back to the main menu.

Nothing in the bottom right in the ConnectIQ app.

**Comment by paulobrien** [comment]
Ah, apologies, I forgot that! I'll check on the emulator when I get home, but maybe long press the middle left button?

**Comment by purcell-lab** [comment]
:

> Ah, apologies, I forgot that! I'll check on the emulator when I get home,
> but maybe long press the middle left button?
>
Thanks long press on middle left button works!

Perhaps you could document in the readme.

>
