### ISSUE TITLE
Error -2 on FR645M

### ISSUE THREAD

**Issue by mrwolf78** [srwalter/garmin-tesla#8]
I try to get this widget up and running on my Forerunner 645M, but I keep getting an error: -2.

In the IQ app I tried adding the API-token (which works for other apps, even retried a new token)
I open the widget, and press start to wake the vehicle. 
The text 'getting vehicles' appears
after 30 seconds or so, the error -2 is shown

What am I doing wrong?

**Comment by paulobrien** [comment]
This device tests OK in the simulator with the latest version, please confirm if you are still having issues!

**Comment by mrwolf78** [comment]
I don't own the FR645M anymore, so I can't test it
